### ISSUE TITLE
Do not rely on setup.cfg for configuration

### ISSUE THREAD

**Issue by romainrichard** [adamchainz/multilint#17]
Not every Python project uses setuptools, sometimes all you have is a standalone script. It would be nice if we could still run multilint in those cases.

My suggestion is to have `~/.config/multilint` for system-wide config and allow those defaults to be overwritten by a project using a `.multilint` file at the root of the project (i.e. something like `~/projects/my_project1/.multilint`.

That last part will conflict with `setup.cfg` and `tox.ini` so there will need to be some rule about precedence.

**Comment by adamchainz** [comment]
The main reason I use `setup.cfg` is because most of the linters `multilint` runs support reading their config out of `setup.cfg`, so projects can have a single file. In this case using `setup.cfg` still makes sense as you can centralize your flake8, multilint, isort, etc. config in one file. I don't really like the idea of adding 'yet another' standard for such a small utility :/
